<a href="https://colab.research.google.com/github/dinhtrung0706/esg_lakehouse/blob/feat%2FcleanProd_n_RawMat/Clean_DT%26EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import pandas as pd

# Loads every sheet into a dict: {"Sheet1": df1, "Sheet2": df2, ...}
all_sheets = pd.read_excel("DV.xlsx", sheet_name=None)
for name, df in all_sheets.items():
    df.to_csv(f"{name}.csv", index=False)

In [47]:
df = pd.read_csv("Production, Raw Mat.csv", header=None)
print(df.shape)
print(df.to_string())  # see everything — find where table 2 starts

(21, 19)
                                                                                               0           1                    2                     3                    4                     5                    6                    7                    8                    9                    10                   11                  12                    13                   14                   15                   16                   17                   18
0                                                                                      Unnamed: 0  Unnamed: 1           Unnamed: 2            Unnamed: 3           Unnamed: 4            Unnamed: 5           Unnamed: 6           Unnamed: 7           Unnamed: 8           Unnamed: 9          Unnamed: 10          Unnamed: 11         Unnamed: 12           Unnamed: 13          Unnamed: 14          Unnamed: 15          Unnamed: 16          Unnamed: 17          Unnamed: 18
1                                                                Production (DV Tile + YB Powder)        unit                  Jan                   Feb                  Mar                   Apr                  May                  Jun                  Jul                  Aug                  Sep                  Oct                 Nov                   Dec                  YTD                   Q1                   Q2                   Q3                   Q4
2                                                              Production (DV Tile) (Sản phẩm ĐV)         ton             9609.931      6310.08093333333     17732.9734666667    15795.455366666702     16091.7997666667   16408.015833333302     18454.3238047619      16179.630247619     12136.7603666667       12464.84121625  12324.145550000001    15580.268823333301    169088.2263752976   33652.985400000034    48295.27096666671   46770.714419047596    40369.25558958331
3                                                   Production (YB Powder) (bột bán cho Yên Bình)         ton                    0                     0                    0                     0                    0                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN    423.66740000000004   423.66740000000004                    0                    0                    0   423.66740000000004
4                                                                      Total Production (DV + YB)         ton             9609.931      6310.08093333333     17732.9734666667    15795.455366666702     16091.7997666667   16408.015833333302     18454.3238047619      16179.630247619     12136.7603666667       12464.84121625  12324.145550000001    16003.936223333301   169511.89377529762   33652.985400000034    48295.27096666671   46770.714419047596   40792.922989583305
5                                                                                             NaN         NaN                  NaN                   NaN                  NaN                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN
6                                                                                    Raw Material        unit                  Jan                   Feb                  Mar                   Apr                  May                  Jun                  Jul                  Aug                  Sep                  Oct                 Nov                   Dec                  YTD                   Q1                   Q2                   Q3                   Q4
7                                                                      Limestone/ Đá vôi (canxit)         ton              1185.21                903.63             2451.735              2133.495              2066.22             2160.795             2501.265              2094.69              1523.34             1624.155             1624.35               1872.75            22141.635    4540.575000000001              6360.51             6119.295             5121.255
8                                                                                   Clay/ Đất sét         ton              6280.95                4812.6             13112.58              11433.24            11029.452             11323.65            13526.175            12506.465              8783.97              9729.72            9687.405             11518.615           123744.822   24206.129999999997            33786.342             34816.61   30935.739999999998
9                                                                                       Sand/ Cát         ton                  NaN                   NaN                  NaN                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                   NaN                    0                    0                    0                    0                    0
10                                                                              Gypsum/ Thạch cao         ton                  NaN                   NaN                  NaN                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                   NaN                    0                    0                    0                    0                    0
11                                                                               Laterite/ Đá ong         ton                  NaN                   NaN                  NaN                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                   NaN                    0                    0                    0                    0                    0
12                                                                                Cement/ Xi măng         ton                  NaN                   NaN                  NaN                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                   NaN                    0                    0                    0                    0                    0
13                                                                                       Feldspar         ton               696.15                 772.2               1762.8               1414.14             1600.308              1814.67              2458.17                963.3               958.62                877.5               627.9                1141.7            15087.458   3231.1499999999996             4829.118              4380.09   2647.1000000000004
14                                                                         Aggregate/ Chất kết tụ         ton                  NaN                   NaN                  NaN                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                   NaN                    0                    0                    0                    0                    0
15                                                                                  Pottery Stone         ton                  NaN                   NaN                  NaN                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                   NaN                    0                    0                    0                    0                    0
16                                                              Glazing (Men ướt nhập VP quy khô)         ton               611.66               593.122             1366.899              1232.648             1224.313             1274.894             1532.653             1223.418              908.336              1025.46             906.515              1268.747   13168.664999999997   2571.6809999999996   3731.8550000000005             3664.407   3200.7219999999998
17  Recycled Mat/ Nguyên liệu tái sử dụng (gạch tái sử dụng+bột mài, bột liệu ép, xỉ than tái SD)         ton               625.13                364.14              1105.56                1051.7    989.6100000000001              1257.75              1428.32   1273.5349999999999              917.475               881.01              917.28    1021.9799999999999             11833.49              2094.83   3299.0600000000004   3619.3299999999995              2820.27
18                                                                       Others/ Nguyên liệu khác         ton                  NaN                   NaN                  NaN                   NaN                  NaN                  NaN                  NaN                  NaN                  NaN                  NaN                 NaN                   NaN                    0                    0                    0                    0                    0
19                                                          Total raw materials/ Tổng nguyên liệu         ton    9399.099999999999     7445.692000000001   19799.574000000004    17265.222999999998            16909.903            17831.759            21446.583            18061.408            13091.741            14137.845            13763.45             16823.792            185976.07    36644.36600000001   52006.884999999995   52599.731999999996            44725.087
20                                                                    % Alternative raw materials           %  0.06650955942590249  0.048906132566321564  0.05583756499003462  0.060914359461212875  0.05852251192688688  0.07053426417438684  0.06659895424832944  0.07051139091703149  0.07008044231855794  0.06231572067737339   0.066646080742837  0.060746114787914626  0.06362910023854144  0.05716649593555526  0.06343506249220658  0.06880890571837894  0.06305789857938118

In [48]:
# Find the blank row that separates the two tables
blank_rows = df[df.isnull().all(axis=1)].index.tolist()
print("Blank rows at:", blank_rows)  # e.g., [15] means split at row 15

Blank rows at: [5]

In [49]:
split = blank_rows[0]  # e.g., row 15

raw_prod = df.iloc[:split].copy()
raw_mat  = df.iloc[split+1:].copy()  # +1 to skip the blank row

In [50]:
# First row is header
prod = raw_prod.copy()
prod.columns = prod.iloc[1]    # set header
prod = prod.iloc[2:].reset_index(drop=True)

# Separate the total row (last row)
prod_total = prod.iloc[[-1]]   # keep for reference
prod_data  = prod.iloc[:-1]    # actual data without total

prod_data.columns.name = None
prod_data.head()

,Production (DV Tile + YB Powder),unit,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,YTD,Q1,Q2,Q3,Q4
0,Production (DV Tile) (Sản phẩm ĐV),ton,9609.931,6310.08093333333,17732.9734666667,15795.455366666702,16091.7997666667,16408.015833333302,18454.3238047619,16179.630247619,12136.7603666667,12464.84121625,12324.145550000001,15580.268823333301,169088.2263752976,33652.985400000034,48295.27096666671,46770.714419047596,40369.25558958331
1,Production (YB Powder) (bột bán cho Yên Bình),ton,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,423.66740000000004,423.66740000000004,0,0,0,423.66740000000004

In [51]:
raw = raw_mat.copy()
raw.columns = raw.iloc[0]      # set header
raw = raw.iloc[1:].reset_index(drop=True)

# Last 2 rows = total + alt raw mat percentage
raw_total      = raw.iloc[[-2]]   # total row
raw_pct        = raw.iloc[[-1]]   # % alt raw mat row
raw_data       = raw.iloc[:-2]    # actual data

raw_data.columns.name = None
raw_data.head()

,Raw Material,unit,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,YTD,Q1,Q2,Q3,Q4
0,Limestone/ Đá vôi (canxit),ton,1185.21,903.63,2451.735,2133.495,2066.22,2160.795,2501.265,2094.69,1523.34,1624.155,1624.35,1872.75,22141.635,4540.575000000001,6360.51,6119.295,5121.255
1,Clay/ Đất sét,ton,6280.95,4812.6,13112.58,11433.24,11029.452,11323.65,13526.175,12506.465,8783.97,9729.72,9687.405,11518.615,123744.822,24206.129999999997,33786.342,34816.61,30935.739999999998
2,Sand/ Cát,ton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
3,Gypsum/ Thạch cao,ton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
4,Laterite/ Đá ong,ton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0

In [52]:
def clean_columns(df):
    cols = list(df.columns)
    cols[0] = "name"
    cols[1] = "unit"
    df.columns = cols
    return df

prod_data = clean_columns(prod_data)
raw_data  = clean_columns(raw_data)

In [53]:
prod_data.head()

,name,unit,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,YTD,Q1,Q2,Q3,Q4
0,Production (DV Tile) (Sản phẩm ĐV),ton,9609.931,6310.08093333333,17732.9734666667,15795.455366666702,16091.7997666667,16408.015833333302,18454.3238047619,16179.630247619,12136.7603666667,12464.84121625,12324.145550000001,15580.268823333301,169088.2263752976,33652.985400000034,48295.27096666671,46770.714419047596,40369.25558958331
1,Production (YB Powder) (bột bán cho Yên Bình),ton,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,423.66740000000004,423.66740000000004,0,0,0,423.66740000000004

In [54]:
raw_data.head()

,name,unit,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,YTD,Q1,Q2,Q3,Q4
0,Limestone/ Đá vôi (canxit),ton,1185.21,903.63,2451.735,2133.495,2066.22,2160.795,2501.265,2094.69,1523.34,1624.155,1624.35,1872.75,22141.635,4540.575000000001,6360.51,6119.295,5121.255
1,Clay/ Đất sét,ton,6280.95,4812.6,13112.58,11433.24,11029.452,11323.65,13526.175,12506.465,8783.97,9729.72,9687.405,11518.615,123744.822,24206.129999999997,33786.342,34816.61,30935.739999999998
2,Sand/ Cát,ton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
3,Gypsum/ Thạch cao,ton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
4,Laterite/ Đá ong,ton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0

In [55]:
time_cols = [c for c in prod_data.columns if c not in ["name", "unit"]]

prod_long = prod_data.melt(
    id_vars=["name", "unit"],
    value_vars=time_cols,
    var_name="period",
    value_name="value"
)

raw_long = raw_data.melt(
    id_vars=["name", "unit"],
    value_vars=time_cols,
    var_name="period",
    value_name="value"
)

In [56]:
prod_long.head()

                                            name unit period             value
0             Production (DV Tile) (Sản phẩm ĐV)  ton    Jan          9609.931
1  Production (YB Powder) (bột bán cho Yên Bình)  ton    Jan                 0
2             Production (DV Tile) (Sản phẩm ĐV)  ton    Feb  6310.08093333333
3  Production (YB Powder) (bột bán cho Yên Bình)  ton    Feb                 0
4             Production (DV Tile) (Sản phẩm ĐV)  ton    Mar  17732.9734666667

In [57]:
for df in [prod_long, raw_long]:
    df["value"] = pd.to_numeric(df["value"], errors="coerce")
    df["value"] = df["value"].fillna(0)

In [58]:
prod_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    34 non-null     object
 1   unit    34 non-null     object
 2   period  34 non-null     object
 3   value   34 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.2+ KB

In [59]:
prod_long

                                             name unit period          value
0              Production (DV Tile) (Sản phẩm ĐV)  ton    Jan    9609.931000
1   Production (YB Powder) (bột bán cho Yên Bình)  ton    Jan       0.000000
2              Production (DV Tile) (Sản phẩm ĐV)  ton    Feb    6310.080933
3   Production (YB Powder) (bột bán cho Yên Bình)  ton    Feb       0.000000
4              Production (DV Tile) (Sản phẩm ĐV)  ton    Mar   17732.973467
5   Production (YB Powder) (bột bán cho Yên Bình)  ton    Mar       0.000000
6              Production (DV Tile) (Sản phẩm ĐV)  ton    Apr   15795.455367
7   Production (YB Powder) (bột bán cho Yên Bình)  ton    Apr       0.000000
8              Production (DV Tile) (Sản phẩm ĐV)  ton    May   16091.799767
9   Production (YB Powder) (bột bán cho Yên Bình)  ton    May       0.000000
10             Production (DV Tile) (Sản phẩm ĐV)  ton    Jun   16408.015833
11  Production (YB Powder) (bột bán cho Yên Bình)  ton    Jun       0.000000
12             Production (DV Tile) (Sản phẩm ĐV)  ton    Jul   18454.323805
13  Production (YB Powder) (bột bán cho Yên Bình)  ton    Jul       0.000000
14             Production (DV Tile) (Sản phẩm ĐV)  ton    Aug   16179.630248
15  Production (YB Powder) (bột bán cho Yên Bình)  ton    Aug       0.000000
16             Production (DV Tile) (Sản phẩm ĐV)  ton    Sep   12136.760367
17  Production (YB Powder) (bột bán cho Yên Bình)  ton    Sep       0.000000
18             Production (DV Tile) (Sản phẩm ĐV)  ton    Oct   12464.841216
19  Production (YB Powder) (bột bán cho Yên Bình)  ton    Oct       0.000000
20             Production (DV Tile) (Sản phẩm ĐV)  ton    Nov   12324.145550
21  Production (YB Powder) (bột bán cho Yên Bình)  ton    Nov       0.000000
22             Production (DV Tile) (Sản phẩm ĐV)  ton    Dec   15580.268823
23  Production (YB Powder) (bột bán cho Yên Bình)  ton    Dec     423.667400
24             Production (DV Tile) (Sản phẩm ĐV)  ton    YTD  169088.226375
25  Production (YB Powder) (bột bán cho Yên Bình)  ton    YTD     423.667400
26             Production (DV Tile) (Sản phẩm ĐV)  ton     Q1   33652.985400
27  Production (YB Powder) (bột bán cho Yên Bình)  ton     Q1       0.000000
28             Production (DV Tile) (Sản phẩm ĐV)  ton     Q2   48295.270967
29  Production (YB Powder) (bột bán cho Yên Bình)  ton     Q2       0.000000
30             Production (DV Tile) (Sản phẩm ĐV)  ton     Q3   46770.714419
31  Production (YB Powder) (bột bán cho Yên Bình)  ton     Q3       0.000000
32             Production (DV Tile) (Sản phẩm ĐV)  ton     Q4   40369.255590
33  Production (YB Powder) (bột bán cho Yên Bình)  ton     Q4     423.667400

In [60]:
prod_long.name

0                Production (DV Tile) (Sản phẩm ĐV)
1     Production (YB Powder) (bột bán cho Yên Bình)
2                Production (DV Tile) (Sản phẩm ĐV)
3     Production (YB Powder) (bột bán cho Yên Bình)
4                Production (DV Tile) (Sản phẩm ĐV)
5     Production (YB Powder) (bột bán cho Yên Bình)
6                Production (DV Tile) (Sản phẩm ĐV)
7     Production (YB Powder) (bột bán cho Yên Bình)
8                Production (DV Tile) (Sản phẩm ĐV)
9     Production (YB Powder) (bột bán cho Yên Bình)
10               Production (DV Tile) (Sản phẩm ĐV)
11    Production (YB Powder) (bột bán cho Yên Bình)
12               Production (DV Tile) (Sản phẩm ĐV)
13    Production (YB Powder) (bột bán cho Yên Bình)
14               Production (DV Tile) (Sản phẩm ĐV)
15    Production (YB Powder) (bột bán cho Yên Bình)
16               Production (DV Tile) (Sản phẩm ĐV)
17    Production (YB Powder) (bột bán cho Yên Bình)
18               Production (DV Tile) (Sản phẩm ĐV)
19    Production (YB Powder) (bột bán cho Yên Bình)
20               Production (DV Tile) (Sản phẩm ĐV)
21    Production (YB Powder) (bột bán cho Yên Bình)
22               Production (DV Tile) (Sản phẩm ĐV)
23    Production (YB Powder) (bột bán cho Yên Bình)
24               Production (DV Tile) (Sản phẩm ĐV)
25    Production (YB Powder) (bột bán cho Yên Bình)
26               Production (DV Tile) (Sản phẩm ĐV)
27    Production (YB Powder) (bột bán cho Yên Bình)
28               Production (DV Tile) (Sản phẩm ĐV)
29    Production (YB Powder) (bột bán cho Yên Bình)
30               Production (DV Tile) (Sản phẩm ĐV)
31    Production (YB Powder) (bột bán cho Yên Bình)
32               Production (DV Tile) (Sản phẩm ĐV)
33    Production (YB Powder) (bột bán cho Yên Bình)
Name: name, dtype: object

In [61]:
import re

# Vietnamese character set
viet_chars = (
    r'àáâãèéêìíòóôõùúýăđơư'
    r'ạảấầẩẫậắằẳẵặẹẻẽếềểễệ'
    r'ỉịọỏốồổỗộớờởỡợụủứừửữự'
    r'ỳỵỷỹÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚÝĂĐƠƯ'
)

def remove_vietnamese(text):
    if not isinstance(text, str):
        return text

    # Remove name0, name1 prefix
    text = re.sub(r'^name\d+', '', text)

    # Pattern 1: Remove last Vietnamese parenthesis → (Sản phẩm ĐV)
    viet_paren = rf'\s*\([^)]*[{viet_chars}][^)]*\)'
    text = re.sub(viet_paren, '', text)

    # Pattern 2: Remove slash + Vietnamese → / Đá vôi (canxit)
    # Cuts everything from / onwards if what follows contains Vietnamese
    slash_viet = rf'\s*/[^/]*[{viet_chars}].*'
    text = re.sub(slash_viet, '', text)

    return text.strip()

# Test
samples = [
    "Production (DV Tile) (Sản phẩm ĐV)",
    "Production (YB Powder) (bột bán cho Yên Bình)"
]

for s in samples:
    print(remove_vietnamese(s))
# → Production (DV Tile)
# → Production (YB Powder)

Production (DV Tile)
Production (YB Powder)

In [62]:
# Clean the name column
prod_long["name"] = prod_long["name"].apply(remove_vietnamese)
raw_long["name"]  = raw_long["name"].apply(remove_vietnamese)

# If column headers themselves have Vietnamese
prod_long.columns = [remove_vietnamese(c) for c in prod_long.columns]
raw_long.columns  = [remove_vietnamese(c) for c in raw_long.columns]

In [63]:
prod_long

                      name unit period          value
0     Production (DV Tile)  ton    Jan    9609.931000
1   Production (YB Powder)  ton    Jan       0.000000
2     Production (DV Tile)  ton    Feb    6310.080933
3   Production (YB Powder)  ton    Feb       0.000000
4     Production (DV Tile)  ton    Mar   17732.973467
5   Production (YB Powder)  ton    Mar       0.000000
6     Production (DV Tile)  ton    Apr   15795.455367
7   Production (YB Powder)  ton    Apr       0.000000
8     Production (DV Tile)  ton    May   16091.799767
9   Production (YB Powder)  ton    May       0.000000
10    Production (DV Tile)  ton    Jun   16408.015833
11  Production (YB Powder)  ton    Jun       0.000000
12    Production (DV Tile)  ton    Jul   18454.323805
13  Production (YB Powder)  ton    Jul       0.000000
14    Production (DV Tile)  ton    Aug   16179.630248
15  Production (YB Powder)  ton    Aug       0.000000
16    Production (DV Tile)  ton    Sep   12136.760367
17  Production (YB Powder)  ton    Sep       0.000000
18    Production (DV Tile)  ton    Oct   12464.841216
19  Production (YB Powder)  ton    Oct       0.000000
20    Production (DV Tile)  ton    Nov   12324.145550
21  Production (YB Powder)  ton    Nov       0.000000
22    Production (DV Tile)  ton    Dec   15580.268823
23  Production (YB Powder)  ton    Dec     423.667400
24    Production (DV Tile)  ton    YTD  169088.226375
25  Production (YB Powder)  ton    YTD     423.667400
26    Production (DV Tile)  ton     Q1   33652.985400
27  Production (YB Powder)  ton     Q1       0.000000
28    Production (DV Tile)  ton     Q2   48295.270967
29  Production (YB Powder)  ton     Q2       0.000000
30    Production (DV Tile)  ton     Q3   46770.714419
31  Production (YB Powder)  ton     Q3       0.000000
32    Production (DV Tile)  ton     Q4   40369.255590
33  Production (YB Powder)  ton     Q4     423.667400

In [64]:
raw_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    204 non-null    object
 1   unit    204 non-null    object
 2   period  204 non-null    object
 3   value   204 non-null    float64
dtypes: float64(1), object(3)
memory usage: 6.5+ KB

In [68]:
raw_long

              name unit period     value
0        Limestone  ton    Jan  1185.210
1             Clay  ton    Jan  6280.950
2             Sand  ton    Jan     0.000
3           Gypsum  ton    Jan     0.000
4         Laterite  ton    Jan     0.000
..             ...  ...    ...       ...
199      Aggregate  ton     Q4     0.000
200  Pottery Stone  ton     Q4     0.000
201        Glazing  ton     Q4  3200.722
202   Recycled Mat  ton     Q4  2820.270
203         Others  ton     Q4     0.000

[204 rows x 4 columns]

In [69]:
raw_long.to_csv("raw_long_cleaned.csv", index=False)
prod_long.to_csv("prod_long_cleaned.csv", index=False)